### ISSUE TITLE
DB: Ensure dbhandler Query and Exec are able to return error

### ISSUE THREAD

**Issue by kluthen** [kluthen/upsilon_cities_go#19]
ATM on error when calling Query or Exec app crash with log.Fatalxxx 

While it's nice to crash early ... not sure it's quite that nice ;)
Add error to possible output of Query & Exec, with a nice(and appropriate) message.

**Comment by ludoc17** [comment]
#110 refactor to return error on query and go up.

**Comment by ludoc17** [comment]
Add function in tools to return error in API Avec indication DEbug user admin etc..
