### ISSUE TITLE
Grid: City overrode by Roads ;)

### ISSUE THREAD

**Issue by kluthen** [kluthen/upsilon_cities_go#31]
Sometimes, a city get "overrode" by a road ... guess that's a grid generator problem... :'( :'(

To see this in effect, generate a map, hover on a city, you may observe sometimes city appearing where a road is ;)

**Comment by ludoc17** [comment]
![image](https://user-images.githubusercontent.com/35073850/57584545-057a3400-74dd-11e9-9ae8-cfec8e38ad49.png)

**Comment by ludoc17** [comment]
never seen it happen anymore.
I was maybe on a branch without the BugFix
