### ISSUE TITLE
Web: Evaluate JS UI builder

### ISSUE THREAD

**Issue by kluthen** [kluthen/upsilon_cities_go#34]
ATM "dynamic" views are handled server side and ajaxed to the client. 
must be said that go templating system is archaic at best ;)

we produce an API as well, so why not use it for UI rendering ?

Check JS UI for usability ( React.js, Vue.js, ... ): main acceptance criteria:  Must be **easier** than actual templating system, but allow bit more flexibility ( conditions, iterations, minor computation ) ; **Ease of use** ( must not have to write 3 pages of codes for simple things, nor reading 10 books of doc ) ;

**Comment by ludoc17** [comment]
vue.js and phaser3 will do the trick for now.
Maybe thinks about it again later on
