### ISSUE TITLE
Review caravan feature ... 

### ISSUE THREAD

**Issue by kluthen** [kluthen/upsilon_cities_go#66]
Lacks forethought on this one #46 : 

* how ? Process to sell some ressource to somebody else ( be it computer or player handled ) 
  * original proposition was: set up delay ( player must validate or refuse by 20 cycles (that's short ;p )  ... computer owned cities simply says OKAY when price is right ... 
  * But maybe we could have some alt buying / reselling to player ... like : we sell to "the market of the city x" and owner of city x may choose later on to buy stuff from market ... market get recycled every few hours ...  ??
    * thus selling is quick 
    * loosing money only when player need it and not when other player suggest it ...
* why import ressources ? ( loose money ? fill up storage space ?? ) 
  * maybe we should note rarity of the product  ( number of producer of a type/name within region) and have it influence price and/or fame gain ...  ??
  * Maybe add option just like sell items (for creds) and sell items for fame (like give it to the population) ... This could top up fame quickly in owner city ??

**Comment by kluthen** [comment]
Also means, how to ensure that computer owned cities do exchange occasionnaly ... we don't need really sofisticated AI for this ... but it need to live, otherwise player owned cities won't be able to perform as nicely ...

**Comment by ludoc17** [comment]
maybe caravan should permit recurring trade exchange of ressource between two city on round-trip delay.
between player : 
A player set a proposal for an other player that can be agreed or not and stop on both side after a min of x round set on the proposal.
that will help factory creation and create more complex flux to deal with for player .
But AI need to be a bit more complex to see if trade is interresting depending on rarity and disponibility of product.

**Comment by kluthen** [comment]
Like it

Player 1 send to player 2 :

Exchange item A against item B
Ratio 2:3. Max item per trip set as well. 
A quality within bounds
B quality within bounds
A Base price set 
B base price set

Delay between trips( to and back; between 2 trip as well) are to be set as well. 


Penalty for non delivery or partial delivery: money, + fame loss + contract broken

Means if A send 200 items. B should send back 300 items or suffer penalty

Proposition open for a day. 

Of course computer controlled cities should allow or initiate caravan but using items default base price. 

Note intra corporation exchange should be allowed. Player Corp only. 
And may be unbalanced.  But will still use caravan slot on initiating city 

Barcaioni Bastien

**Comment by kluthen** [comment]
By base price I mean one could compensate a lower good with more money.

Item 1 is low grad but want to by item 2 with it ... May compensate money loss on player 2 by adding money to the trade. 

Barcaioni Bastien
