### ISSUE TITLE
City: CityID or MapID/CityID Key

### ISSUE THREAD

**Issue by ludoc17** [kluthen/upsilon_cities_go#69]
We need to chose if we use CityID or MapID/CityID  as an identifier for city.
And change code to be coherent.

Now : 
Db use CityID as PrimaryKey
City Struct have only cityID
Handler use City but in generation need to get MapID back from db
API use MapID/CityID even if he doesn't need mapID

**Comment by kluthen** [comment]
Soooo whether we keep dependency to map or not in api/non api routes ...

If city struct has a link to map. It s okay to remove the map dependency in routes. 
So long we don't have route targeting all cities of a map. 

Have fun ^^ also using named routes would have prevented the need to rewrite controllers for this ^^
